---
- name: Enable automatic security updates on Ubuntu CTs
  hosts: ct
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_become_password: "{{ vault_naruby_password }}"
    ansible_user: "{{ ct_user }}"
  tags:
    - ct
  tasks:
    - name: Install unattended-upgrades package
      ansible.builtin.apt:
        name: unattended-upgrades
        state: present
        update_cache: true

    - name: Configure unattended-upgrades for security updates only
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/50unattended-upgrades
        content: |
          // Automatically upgrade packages from these (origin:archive) pairs
          Unattended-Upgrade::Allowed-Origins {
            "${distro_id}:${distro_codename}-security";
          };

          // Minimal steps during unattended-upgrades
          Unattended-Upgrade::MinimalSteps "true";

          // Disable automatic reboot by default
          Unattended-Upgrade::Automatic-Reboot "false";
        owner: root
        group: root
        mode: '0644'

    - name: Configure periodic APT actions
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/20auto-upgrades
        content: |
          // Enable daily package list updates and unattended upgrades
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
        owner: root
        group: root
        mode: '0644'

    - name: Ensure unattended-upgrades service is enabled and running
      ansible.builtin.service:
        name: unattended-upgrades
        enabled: true
        state: started
