- name: Update & upgrade Ubuntu CTs
  hosts: 
    - ct
    - unify
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_become_password: "{{ vault_naruby_password }}"
    ansible_user: "{{ ct_user }}"

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Perform dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
