
- name: Manage CT containers
  hosts: homelab
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Ensure proxmoxer and requests are installed
      ansible.builtin.pip:
        name:
          - proxmoxer
          - requests
        state: present
        executable: pip3
      delegate_to: localhost
      run_once: true
  tags:
    - ct-control
  collections:
    - community.general
  vars:
    proxmox_api_key: "{{ vault_proxmox_password }}"
    proxmox_api_user: "{{ vault_proxmox_user }}"
    proxmox_validate_certs: false
  tasks:
    - name: "Start CT containers"
      tags:
        - start_ct
      community.general.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_key }}"
        api_host: "{{ ansible_host }}"
        vmid: "{{ hostvars[item].vmid }}"
        state: started
        validate_certs: "{{ proxmox_validate_certs }}"
        timeout: 300
      loop: "{{ groups['ct'] }}"

    - name: Stop CT containers
      tags:
        - stop_ct
      community.proxmox.proxmox:
        api_user: "{{ proxmox_api_user }}"
        api_password: "{{ proxmox_api_key }}"
        api_host: "{{ ansible_host }}"
        vmid: "{{ hostvars[item].vmid }}"
        state: stopped
        validate_certs: "{{ proxmox_validate_certs }}"
        timeout: 300
      loop: "{{ groups['ct'] }}"
