---
- name: Update & upgrade Ubuntu CTs
  hosts: ct
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_become_password: "{{ vault_naruby_password }}"
    ansible_python_interpreter: /usr/bin/python3
  tags:
    - ct
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Perform dist-upgrade
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true

- name: Update & upgrade CentOS oVirt hosts
  hosts: ovirt
  become: true
  become_method: ansible.builtin.sudo
  vars:
    ansible_become_password: "{{ vault_naruby_password }}"

  tags:
    - ovirt
  tasks:
    - name: Ensure all packages are up to date
      ansible.builtin.dnf:
        name: "*"
        state: latest
