---
- name: Start containers
  hosts: homelab
  strategy: linear
  connection: local
  gather_facts: false
  tags:
    - ct-start
  vars:
    proxmox_api_key: "{{ vault_proxmox_password }}"
    proxmox_api_user: "{{ vault_proxmox_user }}"
    proxmox_validate_certs: false
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  tasks:
    - name: Include start_ct tasks
      ansible.builtin.include_tasks: tasks/start_ct.yml

- name: Create user
  hosts: ct
  remote_user: root
  gather_facts: false
  tags:
    - ct-create-user
  vars:
    ansible_user: root
  tasks:
    - name: Include create_user tasks
      ansible.builtin.include_tasks: tasks/create_user.yml

- name: Update & upgrade CTs
  hosts:
    - ct
    - unify
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - ct-update
    - ct-upgrade
  vars:
    ansible_become_password: "{{ vault_naruby_password }}"
    ansible_user: "{{ ct_user }}"
  tasks:
    - name: Include install_updates tasks
      ansible.builtin.include_tasks: tasks/install_updates.yml

- name: Enable automatic security updates on Ubuntu CTs
  hosts: ct
  become: true
  become_method: ansible.builtin.sudo
  tags:
    - ct-enable-auto-updates
  vars:
    ansible_become_password: "{{ vault_naruby_password }}"
    ansible_user: "{{ ct_user }}"
  tasks:
    - name: Include enable_auto_updates tasks
      ansible.builtin.include_tasks: tasks/enable_auto_updates.yml
