- name: Start CT containers
  community.proxmox.proxmox:
    api_user: "{{ proxmox_api_user }}"
    api_password: "{{ proxmox_api_key }}"
    api_host: "{{ ansible_host }}"
    vmid: "{{ hostvars[item].vmid }}"
    state: started
    validate_certs: "{{ proxmox_validate_certs }}"
    timeout: 300
  loop: "{{ groups['ct'] }}"
